### ISSUE TITLE
_tkinter.TclError: bitmap "icons/notepy.ico" not defined

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [Mirko-r/Notepy#2]
Loading module.. Loading user interface.. Error!
I'm running Python 3.9.7 notepy.py.
(Solus Budgie Linux 4.3)

Pip freeze:
```
aiohttp==3.7.4.post0
apparmor==3.0.1
appdirs==1.4.4
asn1crypto==1.4.0
async-timeout==3.0.1
attrs==21.2.0
beautifulsoup4==4.9.3
black==21.7b0
bs4==0.0.1
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
click==8.0.1
colorama==0.4.4
configobj==5.0.6
cryptography==3.4.7
cssselect==1.1.0
cupshelpers==1.0
discord==1.7.3
discord.py==1.7.3
docopt==0.6.2
fpdf==1.7.2
idna==3.2
joblib==1.0.1
keyboard==0.13.5
LibAppArmor==3.0.1
libevdev==0.9
lxml==4.6.3
markdown2==2.4.1
meson==0.59.1
MouseInfo==0.1.3
multidict==5.1.0
mutagen==1.43.1
mypy-extensions==0.4.3
nltk==3.6.3
num2words==0.5.10
onboard==1.4.1
packaging==20.9
pathspec==0.9.0
pexpect==4.8.0
pocketsphinx==0.1.15
psutil==5.8.0
ptyprocess==0.6.0
pwquality==1.4.2
pyasn1==0.4.8
PyAudio==0.2.11
PyAutoGUI==0.9.53
pycairo==1.20.0
pycparser==2.20
pycups==1.9.74
pygame==2.0.1
pygeoip==0.3.2
PyGetWindow==0.0.9
PyGObject==3.42.0
PyMsgBox==1.0.9
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyperclip==1.8.2
PyQt5==5.15.4
PyQt5-sip==12.9.0
pyquery==1.4.3
PyRect==0.1.4
PyScreeze==0.1.28
PySide2==5.15.2
pysmbc==1.0.15.8
PySocks==1.7.1
python-magic==0.4.22
python3-xlib==0.15
pyttsx3==2.90
pytweening==1.0.4
pyudev==0.22.0
PyYAML==5.1.2
qomui==0.8.2
QtPy==1.9.0
readtime==1.1.1
regex==2021.8.21
requests==2.26.0
shiboken2==5.15.2
sip==6.1.1
six==1.15.0
soupsieve==1.9.6
SpeechRecognition==3.8.1
textblob==0.15.3
tkterminal==0.1.0
toml==0.10.2
tomli==1.2.1
tqdm==4.62.2
typing-extensions==3.10.0.1
urllib3==1.25.6
walkdir==0.4.1
yapf==0.31.0
yarl==1.6.3
youtube-dl==2021.6.6
```

**Comment by TheRedstoneRadiant** [comment]
Full error:
```
Traceback (most recent call last):
  File "/home/user/Notepy/notepy.py", line 73, in progress
    self.main = main.main()
  File "/home/user/Notepy/main.py", line 29, in main
    root.iconbitmap("icons/notepy.ico")
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "icons/notepy.ico" not defined

```

**Comment by Mirko-r** [comment]
I fixed the problem in the main.py file
Try to:

- clone the repo again
- follow the new setup instruction

Let me know if it wotk for you

**Comment by TheRedstoneRadiant** [comment]
Same error, unfortunately.

**Comment by Mirko-r** [comment]
In the list of modules you posted above, tkinter is missing

**Comment by Mirko-r** [comment]
I managed to figure out how to fix this problem, now it's solved do all the steps again and let me know if it works

**Comment by TheRedstoneRadiant** [comment]
Solved
